### PR TITLE
HDBC: Drop Index only if it exists during migration.

### LINKED ISSUE #141: Drop index if exists
Migrations that include `DropIndex` will fail if any of the columns that the index in question references have already been dropped. This is because when one drops a column in postgresql, postgres will also drop indexes and constraints on your behalf.

Consider amending `DropIndex` to perform a `DROP INDEX IF EXISTS`.

### PR DESCRIPTION
**Pull request by telser**
This fixes #141

### CODE REVIEW

File: orville-postgresql/src/Database/Orville/PostgreSQL/Internal/MigrateIndex.hs [hunk 1]
```diff
@@ -39,4 +39,6 @@ createIndexPlan indexDef schemaState = do
 dropIndexPlan :: String -> SchemaState -> Maybe MigrationPlan
 dropIndexPlan name schemaState = do
   guard (schemaStateIndexExists name schemaState)
-  pure $ migrationDDLForItem (DropIndex name) ("DROP INDEX " ++ name)
+  -- Here we drop the index only if it exists so that during the migration plan
+  -- should something else prior cause the index to be dropped we will not cause an error.
+  pure $ migrationDDLForItem (DropIndex name) ("DROP INDEX IF EXISTS" ++ name)
```
Comment (aaronallen8455) [inline orville-postgresql/src/Database/Orville/PostgreSQL/Internal/MigrateIndex.hs:44]: don't you need a space after EXISTS here?

**Review by aaronallen8455 — APPROVED** [review]

File: orville-postgresql/src/Database/Orville/PostgreSQL/Internal/MigrateIndex.hs (hunk 1 above)
Comment (telser) [reply orville-postgresql/src/Database/Orville/PostgreSQL/Internal/MigrateIndex.hs]: mmm I must have deleted it after running my local test, somehow. It's fixed now.
